export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-red">
        <div>{__filename}</div>
        <div>{children}</div>
      </body>
    </html>
  );
}
